### ISSUE TITLE
how to install it

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [otrosien/sonar-perl#4]
Hello,

we are interested in using you sonar plugin to do test on https://www.argonaut-project.org/ who is written in perl. 

Could you give us some instructions on how to install your plugin

Cheers

**Comment by mxlei01** [comment]
There is a gradle build script inside the project. You can build the gradle project, and it will create a java plugin that you need to put inside your sonarqube server. The setup is similar adding plugins for other languages.

**Comment by mxlei01** [comment]
perl critic output is defaulted to "perlcritic.txt".

**Comment by otrosien** [comment]
Sorry, I haven't watched comments on my repo too closely. I'll add some docs once I have a bit of time to continue on this. As for now if you only want to test the plugin, the simplest thing would be to start up the docker container that has sonarqube with this plugin included, by calling `./gradlew sonar-perl-plugin:run`. Otherwise, as @mxlei01 said, do a `gradlew sonar-perl-plugin:build` and copy the resulting jar file `sonar-perl-plugin/build/sonar-perl-plugin-0.1.jar` into the plugins dir of your sonar installation (should be sth. like `/opt/sonarqube/extensions/plugins/`)

**Comment by otrosien** [comment]
Added some documentation on the README.md. I also simplified the use-case of trying out the project, using docker-compose.

**Comment by otrosien** [comment]
BTW: I have just simplified the sample project integration even further. It should be very straight forward for any perl project now to run sonar-scanner based analysis against a local sonarqube by adding this kind of Dockerfile:
https://github.com/otrosien/sonar-perl/blob/master/perl/sample-project/Dockerfile
